# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "d0f416a00e31e62a4d4bb6f4ecc698f9"
name = "fishook"
application_url = "https://buoy-remix-app-rough-glitter-2019.fly.dev/"
embedded = true
handle = "fishook-1"

[webhooks]
api_version = "2025-04"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  uri = "https://sandbox.fishook.online/shopify/webhook"
  compliance_topics = [ "customers/data_request", "customers/redact", "shop/redact" ]

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "customer_read_orders,read_discounts,read_discounts_allocator_functions,read_inventory,read_inventory_shipments,read_inventory_shipments_received_items,read_inventory_transfers,read_orders,read_price_rules,read_product_feeds,read_product_listings,read_products,read_script_tags,unauthenticated_read_customers,unauthenticated_read_product_listings,unauthenticated_read_product_pickup_locations,write_discounts,write_discounts_allocator_functions,write_price_rules,write_products,write_script_tags,write_themes,write_customers"

[auth]
redirect_urls = [
  "https://buoy-remix-app-rough-glitter-2019.fly.dev/auth/callback",
  "https://buoy-remix-app-rough-glitter-2019.fly.dev/auth/shopify/callback",
  "https://buoy-remix-app-rough-glitter-2019.fly.dev/api/auth/callback"
]

[pos]
embedded = false
